-- =============================================
-- MONTH 1 PROJECT QUERIES
-- Retail Shop Database
-- =============================================

-- =============================================
-- BASIC FILTERING Week 1
-- =============================================


-- 1. All products with their category names
SELECT p.product_name, c.category_name, p.price, p.stock_quantity
FROM products p
INNER JOIN categories c ON p.category_id = c.category_id
ORDER BY c.category_name;


-- 2. Products > R1000
SELECT product_name, price
FROM products
WHERE price > 1000
ORDER BY price DESC;


-- 3. Customers from Johannesburg
SELECT first_name, last_name, email FROM customers
WHERE city = 'Johannesburg';


-- 4. Completed orders
SELECT o.order_id, c.first_name, c.last_name, o.order_date
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
WHERE o.status = 'Completed'
ORDER BY o.order_date;


-- =============================================
-- AGGREGATE FUNCTIONS & GROUP BY Week 2
-- =============================================


-- 5. Total number of products per category
SELECT c.category_name, COUNT(p.product_id) AS total_products
FROM categories c
LEFT JOIN products p ON c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY total_products DESC;


-- 6. Total revenue per order
SELECT o.order_id, c.first_name, c.last_name,
    SUM(oi.quantity * oi.unit_price) AS order_total
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, c.first_name, c.last_name
ORDER BY order_total DESC;


-- 7. Total revenue generated by each employee
SELECT e.first_name, e.last_name, e.position,
    SUM(oi.quantity * oi.unit_price) AS total_sales
FROM employees e
INNER JOIN orders o ON e.employee_id = o.employee_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY e.employee_id, e.first_name, e.last_name, e.position
ORDER BY total_sales DESC;


-- 8. Average order value per customer
SELECT c.first_name, c.last_name,
    ROUND(AVG(oi.quantity * oi.unit_price), 2) AS avg_order_value
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY avg_order_value DESC;


-- 9. Departments with more than 1 order processed (HAVING)
SELECT e.first_name, e.last_name,
    COUNT(o.order_id) AS orders_processed
FROM employees e
INNER JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.employee_id, e.first_name, e.last_name
HAVING COUNT(o.order_id) > 1
ORDER BY orders_processed DESC;


-- =============================================
-- JOINS (Week 3)
-- =============================================

-- 10. Full order details: customer, employee, products, quantities
SELECT 
    c.first_name AS customer_name,
    e.first_name AS processed_by,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    (oi.quantity * oi.unit_price) AS line_total,
    o.status
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN employees e ON o.employee_id = e.employee_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
ORDER BY o.order_date;


-- 11. Customers who have never placed an order
SELECT c.first_name, c.last_name, c.email
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- 12. Products that have never been ordered
SELECT p.product_name, p.price, c.category_name
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
LEFT JOIN categories c ON p.category_id = c.category_id
WHERE oi.order_item_id IS NULL;


-- =============================================
-- SUBQUERIES & CTEs (Week 4)
-- =============================================


-- 13. Products priced above the average product price
SELECT product_name, price
FROM products
WHERE price > (SELECT AVG(price) FROM products)
ORDER BY price DESC;


-- 14. Customer who spent the most in a single order
WITH order_totals AS (
    SELECT order_id, SUM(quantity * unit_price) AS order_total
    FROM order_items
    GROUP BY order_id
)
SELECT c.first_name, c.last_name, ot.order_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_totals ot ON o.order_id = ot.order_id
WHERE ot.order_total = (SELECT MAX(order_total) FROM order_totals);


-- 15. CTE: monthly revenue summary
WITH monthly_revenue AS (
    SELECT
        EXTRACT(YEAR FROM o.order_date) AS year,
        EXTRACT(MONTH FROM o.order_date) AS month,
        SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'Completed'
    GROUP BY year, month
)
SELECT year, month, revenue
FROM monthly_revenue
ORDER BY year, month;


-- 16. CTE: top performing employee by sales
WITH employee_sales AS (
    SELECT e.employee_id, e.first_name, e.last_name, e.position,
        SUM(oi.quantity * oi.unit_price) AS total_sales
    FROM employees e
    INNER JOIN orders o ON e.employee_id = o.employee_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY e.employee_id, e.first_name, e.last_name, e.position
),
ranked_employees AS (
    SELECT *, RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
    FROM employee_sales
)
SELECT first_name, last_name, position, total_sales, sales_rank
FROM ranked_employees
ORDER BY sales_rank;


-- =============================================
-- CASE WHEN: business categorisation
-- =============================================


-- 17. Categorise products by price range
SELECT product_name, price,
CASE
    WHEN price >= 5000 THEN 'Premium'
    WHEN price >= 1000 THEN 'Mid-Range'
    WHEN price >= 500 THEN 'Budget'
    ELSE 'Affordable'
END AS price_category
FROM products
ORDER BY price DESC;


-- 18. Order status summary with counts
SELECT status, COUNT(*) AS total_orders,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 1) AS percentage
FROM orders
GROUP BY status;

